### ISSUE TITLE
console error

### ISSUE THREAD

**Issue by rationality6** [smeevil/responsive-block-grid#6]
Hi i'm using your package with self made infinity scrolling

There is and error

Error: “cannot call methods on isotope prior to initialization; attempted to call '___'”

And i found this error's scription

http://isotope.metafizzy.co/faq.html#error-cannot-call-methods-on-isotope-prior-to-initialization-attempted-to-call-___

Could you fix this

**Comment by dferber90** [comment]
The error happens because the query observers never stop running, so it tries to remove elements after the block grid has disappeared from the DOM. To fix it, save the query handle on the template instance and stop it in the `onDestroyed` callback:

https://github.com/smeevil/responsive-block-grid/blob/master/reactive_block_grid.coffee#L60

``` coffee
  if @data.cursor.limit? || @data.cursor.skip?
    # save the handle on the template instance
    @queryHandle = @data.cursor.observeChanges
      addedBefore: -> null
      movedBefore: -> null

      removed: (id) ->
        selector = "[data-reactive-block-grid-item-id=#{id}]"
        item = $el.find(selector)
        $el.isotope('remove', item).isotope('layout')

  else
    @queryHandle = @data.cursor.observe
      removed: (doc) ->
        selector="[data-reactive-block-grid-item-id=#{doc._id}]"
        item=$el.find(selector)
        $el.isotope('remove', item).isotope('layout')

# the important part is stopping it later on
Template.reactiveBlockGrid.destroyed = ()->
  @queryHandle.stop()
```

@smeevil Would you accept a PR fixing this?

**Comment by smeevil** [comment]
@dferber90 Absolutely :)
